Open Source and Update from internal framework
le-phare/import pull request #1
Opened 2023-08-28 12:44 UTC by afrancois-lephare

2023-08-28 16:37 UTC, aegypius requested changes

2023-10-05 09:11 UTC, thislg requested changes

2023-10-05 09:11 UTC, thislg commented on Tests/ImportTest.php
> +
```suggestion
```

2023-10-05 09:11 UTC, thislg commented on composer.json
> +            "dev-main": "2.7-dev"
```suggestion
            "dev-main": "2.0-dev"
```

2023-11-07 15:14 UTC, thislg approved these changes

2023-11-07 15:14 UTC, merged